version: "3"

vars:
  TOOLS_FOLDER: "{{.PWD}}/bin"
  GOLANGCI_LINT_VERSION: v2.2.1
  GOLANGCI_LINT: "{{.TOOLS_FOLDER}}/golangci-lint"
  GOSEC_VERSION: v2.22.4
  GOSEC: "{{.TOOLS_FOLDER}}/gosec"
  GOVULNCHECK: "{{.TOOLS_FOLDER}}/govulncheck"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: unit test {{.BINARY_NAME}}
    cmds:
      - task: fmt
      - task: vet
      - go test $(go list ./...) -coverprofile coverage.out

  fmt:
    desc: run go fmt
    cmds:
      - go fmt $(go list ./...)

  vet:
    desc: run go vet
    cmds:
      - go vet $(go list ./...)

  coverage:
    desc: show global coverage
    cmds:
      - go tool cover -func=coverage.out

  lint:
    desc: run golangci-lint
    cmds:
      - task: golangci-lint
      - "{{.GOLANGCI_LINT}} run"

  lint-fix:
    desc: run golangci-lint and perform fix
    cmds:
      - task: golangci-lint
      - "{{.GOLANGCI_LINT}} run --fix"

  vuln:
    desc: run govulncheck
    cmds:
      - task: govulncheck
      - "{{.GOVULNCHECK}} ./..."

  sec:
    desc: run gosec
    cmds:
      - task: go-sec
      - "{{.GOSEC}} -exclude=G104,G307 ./..."

  module-verify:
    desc: verify modules
    cmds:
      - go mod tidy && go mod verify

  golangci-lint:
    internal: true
    desc: install golangci-lint
    cmds:
      - GOBIN={{.TOOLS_FOLDER}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  go-sec:
    internal: true
    desc: install gosec
    cmds:
      - GOBIN={{.TOOLS_FOLDER}} go install github.com/securego/gosec/v2/cmd/gosec@{{.GOSEC_VERSION}}

  govulncheck:
    internal: true
    desc: install govulncheck
    cmds:
      - GOBIN={{.TOOLS_FOLDER}} go install golang.org/x/vuln/cmd/govulncheck@latest
